version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: andikapri/nodejs:1.0
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "49130:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

