name: SonarQube Analysis

on:
  push:
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install specific ESLint version
      run: npm install eslint@^8.0.0 --save-dev

    - name: Run ESLint
      run: npx eslint .

    - name: Run SonarQube Scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        npx sonar-scanner \
          -Dsonar.projectKey=my-nodejs-app \
          -Dsonar.host.url=https://sonar.rayhan-belajar.my.id \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: andikapri/nodejs:${{ github.run_id }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.29.2'


    - name: Set Image Deployment
      run: |
        sed -i 's/<version>/${{ github.run_id }}/g' deploy-nodejs.yaml

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
        export KUBECONFIG=~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deploy-nodejs.yaml
