name: SonarQube Analysis

on:
  push:
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Required for SonarQube analysis of pull requests

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Or your preferred Node.js version

    - name: Install dependencies
      run: npm install

    - name: Install specific ESLint version
      run: npm install eslint@^8.0.0 --save-dev

    - name: Run ESLint
      run: npx eslint .

#    - name: Run Linter (ESLint)
#      run: npm run lint

    - name: Run SonarQube Scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        npx sonar-scanner \
          -Dsonar.projectKey=my-nodejs-app \
          -Dsonar.host.url=https://sonar.rayhan-belajar.my.id \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}