name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: andikapri
          password: lifeisstruggle

      - name: Build the Docker image
        run: docker build --file Dockerfile --tag andikapri/nodejs:${{ github.run_id }} .

      - name: Push the Docker image
        run: docker push andikapri/nodejs:${{ github.run_id }}   

      - name: Git clone
        run: |
          git remote set-url origin https://andikapri2020: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@github.com/andikapri2020/test-github-action.git
          git clone https://github.com/andikapri2020/test-github-action.git 
          cd test-github-action/sample-app/
          sed -e "s|$(cat andiapp-node.yaml | grep "image:" | awk {'print $2'})|andikapri/nodejs:${{ github.run_id }}|" andiapp-node.yaml
          cat andiapp-node.yaml

          

               